sudo: false
language: node_js
node_js:
- 6
- 4
script: npm run test-ci
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: OZEaSKixTX9pzF/dN1d4PZzSCyu0JW0SYxskgEZnYwiN8fE+njzMbRnmEawMSS+wchr460PIzeeqwRe+w3HAuKF6+/+16hdBePnzf9vGg1vXo9AxzRj4PkN02CSYyzJw3/8Mhhywl0485KN3m4ndbz7Lbb43qff81xaIUBnbcKtrl8OjP2fxdUp0UkghN/u2QPEEG3MM3KaNWnTfPEoJ/uAZt0wnTu0XM9X+sYlaoFy6ZLwick5WArZnIOwr3BGrPxb4LWRhOeLb8x/RTYlFM2pwVdl3camdRqLoo1ylUtaeOpznqh0ECgzL4tgbbFvZeVZRjRUjDFhVHNgbIrevk9V8d01fC5Z3Ez9FAFMzfU8dj3D/9YLHZoe9yxiVGgpoi/gviXweQSGRuSXETev3TaUe+PEq6KkhI79T2OIEgSFmHRx1sdE0/ooFXUDy+fvOD3m7wf/S/XrLOJLfBPLUw0z2jUBv5I20Ky8RcgJ2zIDWmtxvPfOdlVxK6IPM1dVOcImbaxhFU+AcH+6MamDN9uX3Jiwlv2/oKodzRkzMRn3wl07occ8Mo6JnFMeQznwkPh6AmHf/Txtmbevo/S0N1XkDs3LDjmkRuMUJ0t4VBLNZA4pjpn/EILf/8ET3lSseJrN5HijdQTLMHt5gWUCQtNlOzaIYUv7u9+HYrSe/Ocs=
  - secure: XFWKe9v+q5+Qw0RSOf40A3ij/FQy7jzVQXtPwky1LCEH1C8fJO91ir7gz7XqsJrxjZ3//41xKqPbiXxO1OD31Wd92OOHO7gnfz3365VyzGRytZ8AGgwqFsN2GtMpvL9oYFxx85Alw/1SwQByCcVzu+UG2lJPdwbAWjKs3nfoRF0Hff91t9oB4mgMiMy9rBmtaq0HbvHS98C3ySqzbTm8HctzyPHj3KO8clL7jZ9i3BUGTBaEcdMHQKvZoqjCQ/GjN+Qkud9DWUEi7J9O4NzNjOBp5GHmmKjvSAWza/2MRbA9z6uabAK+SCFgCE0T7+4IYLNe7JQe/RCba7U8q4E9rraL+CCGXZxXi5r08OUmQAeDU9OW3xg/5xNFXEG1qTqOlRONPxoRw0hJHaRf7s/Q76/WHXkytPKLTY37v/rpR9uXK1NMFrj60DT+sy5PFVb6HO22BTS5oXe0HwQsIcShha0wsP/lnIlsbCJjH4nBDWnmeKu5WDORKPv2KKB/TmEcHJeMFmac7aC1FOPmvDchrIEja0n2gDAaxH6Srd9Bi1sFmgE/x6hg7u1X/1+M3tOwaGg5OWbVkucdKgqAJ9tlbrFwNP4ZUCExs+GH+Vodi+YgNRINyPylMtv6UlJ8iKLZpttLpw+2TuRHE6qVLPInNbzDF31IfvUEhvxnVCT4pss=
