sudo: false
language: node_js
node_js:
    - stable
    - node
notifications:
    email:
        on_success: never
        on_failure: always
env:
    global:
        - secure: MK6ENjycl3wBF0K3XWp8h4ItgzyzyceBOYqGY676eIJUcHyftfYgOxrEFTPvaOUtl2bEu4Z85rxitL8f7Lixe2hpGVg4/UnU+gLaO6qPbvESGXINsisCi2AcJKmAal6zLQPF71PjgZH1s1pGflOoRvL2CdCuthoN6G5Hl2GcAYoxGEclT9awpMeAi9M0JMxDNx/AMDXKjZanvKZuKWm/GYarvFKJGH0KW7T+OaM21c+9EHf3ogS36vPwp2654RBUhI2SLFqGkd31eUTjWQ3zUh+LXT+j0f7x3o1CDY7q52DrO19smpzTJOvdbZvs1BiJ3HEj5Gfzxo3H5xJY+vIEBCsTsrBC+2gRmXhHVR+Y0xYgRENuHhJf9YvVfmHF4LvQkwDjmQ3MTKqE3JoQt7airlTAB8bR2KdyY3ckCkskcfCTt6M3LZ8ZXcjgbWgZ89nu6ichIu9P2wJxSmVDAWbioXjPOJFMIMV3bYbE5K/CCRKhc45um7fliHD0jMhlDX+Di+SxWG1jc15X2JrBqSe2mej7GijGmrdoEH1TZwJSFHDW3Pce3kzOnSMiGXojOp0ShVbS9i/+6rZm5Dw5V/6oj7VdtsmSyp/qbb9wHGmNBGhpfQz8nsi8dpxoiKXXudHv2VjL8NfL38zLVFYLYxfzyLMeDQnC/T38YdVUr983g2w=
        - secure: RX1WanhWcrVC6iSFVpLIP4W1KA2Psysk79sRdpEd/nO64yXMZmJXjH9akmIuOYiD53ysbY7DdV7JjLbJU12NOBFxbcxQAMsMkLOJt/kH6LG7962NoTmRWBZkN8aw6C8BPAuMgCmMKFoGfEk5WvZMY46uZ9fg6shsW3k5dtBWL6FOiYTyDkaHe6Nd1ibwLV7vgfajWredxF+HtNy75N2DkWN5JDlYg3G88RT4Td4Kj4+Aap2USJ1G/wlXAwXpJrJ9OJ7sLwABzWNGbomhK8IY+L4GupBO/UwZPVzEtaPsH5h7XIg82j3iXzblY4PwdlxafV7iUiTWdQf69uqARjwbqAvH4615VsyeQf8bBrUMtkef08SruGmbWrjIxmjKxfMJ5sk9gmgJhd03bK5VtOzg+FC3+rgwevWFWFp7jood8a4ygRWegv7efRYzWGFNMm7Tm8Kn+GIhUtf0Czk+Jo6PIRVvro4gfCL3xezlMm2Jyqloluo2Qj+KDsb7N8hlPV7umz697+5f0MQJWvf4ubv8meEtzyyLs7C1IrB34OFUhRVVUL0Tjb0uOgJsqohHDrENuNs+2q8+bKVFuEo9PK9YwBYbcQULfezAB18fuBM/9AxZA3TVQsmj2T6jaeHuHBT1l9ngSNrm308SbiXOgB1yQPSWN3Edlgmr1pHN4QIZFIs=
