sudo: false
language: node_js
node_js:
- 6
- 4
script: npm run test-ci
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: iUUWCTqV2ISirM6uifi6KzYrJFdGRBSIIAVmSnzn8AgyIeeI1uqVtVm4Hl1HZ0IJ41XHZ2opLN5R2ABXEdrFGqm60QTRLqNL3GI3kl5djtNMqKDNG41zd6FfuAC/3kToT3km3Z5yV4dlAC7pBZpIyHW/sVfjWrlC8OZxmzQEz1ntDnVsra9DHB3cRRc8QDF4CsBkMyCpw2YmyOwdY2muUDS43rN6lpu3Ey/2vzhv4r+owXKm2HPUa0t4XkaVsuYtLgpkwcoudaF9sNnDjB6pSyKIYpa83UFAwxjWqJzAQ9GrDWs6sWtPIm5fz9unWy1eQMrLgNeZwkpZskJe2mknCsShvAeTXqXkp2WAX/mejzIpOdJFZ9q0+5sQ37GxlvH9nvuPTZhcpzGPQYpVCzuVxbZuf4JMPelIN2erXdZBrvgALbkLJsiitbT80hiVuWeMAxe0YPTFgmFEkfg9SJVUffIFYHLIermR0tjSs2s5fUI3s99E5wwZBft7nszIPESMJPvs9PO3nKb65rPwcT0K+wtGjOWI3aY2NOWMwnckPIu8XDt0zv4r8vdOdUDvJlf1Hx8NmAIsWQjwcNEirgXDufs7I8h0DpeetlX2enQjsKReIeyVhJeR5Iky8xfisE7XuQHBuVVKg/egT+lXR35YAVl0/lWC8EXUJZtQfWb9FP4=
  - secure: N+Fo/F/fb2F7bcf85NGFL3qXTiMQ8F3gBJ9h7PqIi7cHCLe6YXq2dK3g3ddx1qxne+ivAPV3aeWI2awlIz8DEqKLIca4bZ8IcD3OKrr3G8YdDct3UHd/+Fk9/Q1ub4IjUz0O3/svNvngvNpSwEoTZiWnfhedwaMkAuIbtXeevmNmufIby9owjnSzloD4Bkwcc/PYCv67ijQfigcq22eQGWJM0eBqBJ9fAWsmuuSp3K8TcXHfZaGdeJpbC5DRGSXErQ9r8NqtwynnNRbgUPAW1xodLQq2j5QhELyDAohz2bQIJYSfIchH/glY5oUfFxVDTRDEYLT/eQUIF2r/cQrrQ6sYQ9wcbiYPxQELS7FqhcdA++VVLOQ7HJ6tWdDtZeT0XGRgUFAJdErLoEfCHIkkL+F+ciDFx+fDOdXv1/VwcvsXJiJX/TUazzhd0XDsxifd35Yh5kZm2oh+t+yHPDwydKHD9nC0TQZVFFF4WKYwphVGtE968rqiZBpfvjizxPly5NdMCEA3DRqmKRsXMbt62LL3WGsniBdVHGK12dGWmf3m+Iy5Jun937fgipB3vMyF0SDyWQL7JAmiu0v9Qg+h6rftjC2aP1Gat0xQOHWV+4LImNezKCY6d52Zf7iOfcnNGGODc2giWz5dsC7ZZnKeu0woDJDXW2KKG0r2fBt2dJU=
