sudo: false
language: node_js
node_js:
- 6
- 4
script: npm run test-ci
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: Ju/cvFo5rayk+sIFwvXubFHRalFKv0YY8376QUoHhmgySSx7YfKkEtt4L2xuwhUX8qST94Lo0f+U4jRGYIFahmod3r6iOPAX6IcEBJcuI3Oc32x0SCIQgYM+8CEY1iwCHLiDlwkBzRiuDxtIpQ8F84mLj4vnVSwshk0ofLV3Xs6+rbBFlDAZ2qSp4K6PrwYZfzIwAEW7dBWos6lAMCjor1kpnKrcMFbhjI6eB/698lMZUIP5OIjsNrCyU9xuaFUIsfwU+vppse/HkLzbvqPMJ544BEF+gVBFmc+PN6EfgHjaPQFKbEtaJ/bNitOxr8M2HJczWg88yDwRS7NzAPXLBIAJewfJpU9BJheHQj9MFRhSUD56ONQJwozeLlcccnF6HveKEKG/ASzskPNkN9Pq+tW97z6lVLfVo98URz5bMi562zwgPxIxa0aqaiklFc1fRygHz2nZevNUzEkyWpdxGK42zwDXgRZfctPEfkYTbB/v8i1asVy655Q4C5ZVRcMmk380CvyHxMfJX6ova4i5ygW7YV+Ir4w1ocRl0I98bb63MI1gzEl5a8f+WGMAipQsIRBIDv6gIOjr9Ecjdw7o9TfjrocAJMyyIqVXGSuXYLvAhfwibG7EwJSrpGz+HMhxoAbhf/loKDss6+l6jWDSqEYqbQJyR+9Ue+ON9Y3XVAI=
  - secure: tW3Z68tAQiyaNFe9mWJ0Mgs5mE1/vXN9SHTlvu3wT9GDk7rP+NkuUKKPOyOjGw7qvWUFELZQRuqtUkt2onWi9D240XFEFre5eGdRgXfAg6hR7DOb6hXjLKJQA9lwqj/+XMBJvGulUUfghlhDqSnEW4d1EpyuiVgQ9zuF6ITo1ZRF/s/IUAfx5hPC9N1SPt6z0QtD5FZmUnsbutpO04VXRLHy2J/NW9JxqOlKLuDp7a7nM2pDT94pyP/XVz+7PrcexNIxJDXLM8cjyo7dERAhdpzNS3Pvqp+ToEjL8fh2VkEiTolQRK7snSK48Nphmf0867RSNZrZHKyUFiKwByhoY/CsSFJJMliP1XACGhvMwjOQQZnjXyUx5bnudpUPQtcgvO7w9DMJ8UIxIS/+f8Gf2ROwowMNSKkertc0bD/TQB3UIX5kRR/dqk3Qx9odG0xACzkSee/28gMQfADZmxjPbc+gRdyMThxPztolM/sZXoHgd01bGHH7orWZ0BxbotNpigu8LMVwn1+H2qbOEm/uHrz4YmEOjOsi/pYC8J9oww0OuPGaM7MwRnNbDP8+dznrj1Efd6t53uTh5C3lIyYRuS7/nbiv+1VDgImoBY22NAXcUyeZwOhlFCWSNhowbmIhow4wC94kh9BTWbr7b/Wo2Rp+JTG+Ws5YJn0o0e89XVE=
